# Generated by Django 5.1.6 on 2025-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
